### ISSUE TITLE
An extra word on password

### ISSUE THREAD

**Issue by alexpatru** [WebDollar/User-Interface-WebDollar#2]
OS: MacOS Sierra High, Winddows10;
Browsers: Brave, Chorme, Firefox, Safari;
Webdollar version: TestNet #3;

Step to reproduce:
 - open the wallet
 - click the lock icon

Current behaviour:
if you put 12 words, when click set password, an error appears with the message that you have 13 words
if you let the field empty the message said that it's one word.
<img width="598" alt="screen shot 2018-02-10 at 11 02 10" src="https://user-images.githubusercontent.com/17834606/36060579-38526856-0e55-11e8-97a9-1cdb021d9a1a.png">
<img width="585" alt="screen shot 2018-02-10 at 11 03 38" src="https://user-images.githubusercontent.com/17834606/36060580-38709ab0-0e55-11e8-82e5-ac6630e6a58b.png">

@opreacosmind

**Comment by ibudisteanu** [comment]
@opreacosmind didn't you solve this issue in the mean while?

**Comment by opreacosmind** [comment]
Solved.
