### ISSUE TITLE
Mining on Safari doesn't work

### ISSUE THREAD

**Issue by alexpatru** [WebDollar/User-Interface-WebDollar#3]
Webdollar version: Test Net #3

Step to reproduce:
- open webdollar.io on Safari

Current behaviour:
- mining doesn't start

<img width="1440" alt="screen shot 2018-02-13 at 00 36 06" src="https://user-images.githubusercontent.com/17834606/36123635-0650ba1c-1056-11e8-8507-effdac730c8d.png">
<img width="1406" alt="screen shot 2018-02-13 at 00 36 27" src="https://user-images.githubusercontent.com/17834606/36123636-0673087e-1056-11e8-81b0-42a0d54300f8.png">
<img width="1372" alt="screen shot 2018-02-13 at 00 36 41" src="https://user-images.githubusercontent.com/17834606/36123639-0696a914-1056-11e8-9470-93672b48d30b.png">

@ibudisteanu

**Comment by ibudisteanu** [comment]
Hi @alexpatru,

Did you wait 20 seconds to synchronize?

@IonutAlexandruPanait can you test on Safari?

**Comment by ibudisteanu** [comment]
It looks like the User-Interface Bundle didn't  load because the logo is not shown.

Can you also open the console and screenshot the console.log information from the beginning when the website starts?

**Comment by IonutAlexandruPanait** [comment]
@alexpatru We found the problem and we are working now to solve it. Thank you!
@ibudisteanu on safari User Interface bundle is crashing when it is calling the WebDollar Protocol and this is the reason why vue-Frontend also doesn't work.

**Comment by alexpatru** [comment]
@IonutAlexandruPanait Thank you for your answer

**Comment by ibudisteanu** [comment]
Issue solved. Thanks for reporting the issue https://github.com/WebDollar/Node-WebDollar/commit/c49960919d09a4f396b840f2e063388c4014ad43
